name: Docker PostGIS CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [16]
        postgis: ['3.5']
        latest: [false]

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for amd64 and arm64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/postgis
          labels: |
            org.opencontainers.image.title=postgis
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
          tags: |
            type=raw,value=${{ env.VERSION }},enable=true,priority=200
            type=raw,value=latest,enable=${{ matrix.latest }},priority=200

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Multi-platform build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ env.VERSION }}
          file:  ${{ env.VERSION }}/Dockerfile
          tags: |
            ${{ github.repository_owner }}/postgis:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/postgis:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=postgis
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.base.name=docker.io/postgres
          pull: true
          push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
